### ISSUE TITLE
Unable to install on Mibew 3.2.1- Application stopped

### ISSUE THREAD

**Issue by tilkov** [Mibew/geo-ip-plugin#6]
OS: Ubuntu 16.04 LTS, Mibew 3.2.1 GeoIP 1.0.2
Environment: PHP 7.0.32-0ubuntu0.16.04.1 PDO/7.0.32-0ubuntu0.16.04.1 pdo_mysql/7.0.32-0ubuntu0.16.04.1 gd/7.0.32-0ubuntu0.16.04.1 curl/7.0.32-0ubuntu0.16.04.1 mbstring/7.0.32-0ubuntu0.16.04.1 

On installing the plugin, /index.php/operator/plugin produces the following error:
PHP message: PHP Warning:  Application stopped because of uncaught exception vierbergenlars\SemVer\SemVerException "Invalid Version: 7.0.32-0ubuntu0.16.04.1 [[7.0.32-0ubuntu0.16.04.1]]

**Comment by faf** [comment]
Well, it's not the plugin, it's Mibew itself. The issue is caused by the third party library for semantic versioning.

Please, check the solution from this branch: https://github.com/Mibew/mibew/tree/semver_fix

If it will work for you, it will be included in the upcoming release of Mibew Messenger.

**Comment by tilkov** [comment]
Yes, the plug-in can be enabled and used now.
Thank you!

**Comment by faf** [comment]
You're welcome.
